# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: minimal
day_night: true # To turn it on, switch to 'true'
font: ''
font_size: L

# SEO

site_type: Person
local_business_type: ''
org_name: ''
description: ''
twitter: ''

# Contact (edit or remove options as required)

email: abubakarisumaila3@gmail.com
phone: +90 541 726 35 38
address:
  street: Gökalp, 38. Sk. No:8, Zeytinburnu
  city: Istanbul
  region: IST
  postcode: '34020'
  country: Turkey
  country_code: TUR
coordinates:
  latitude: '40.99363'
  longitude: '28.90789'
directions: From street 8, enter Building 1 and take the stairs to room 116 on Floor 2
office_hours:
  - 'Monday 08:30 to 18:30'
  - 'Wednesday 09:00 to 16:30'
appointment_url: 'https://calendly.com'
contact_links:
  - icon: facebook
    icon_pack: fab
    name: Follow on Facebook
    link: 'https://www.facebook.com/sumailasalpawuni'
  - icon: twitter
    icon_pack: fab
    name: DM Me
    link: 'https://twitter.com/SSalpawun'
  - icon: skype
    icon_pack: fab
    name: Skype Me
    link: 'skype:abubakarisumaila3?call'
  - icon: comments
    icon_pack: fas
    name: Discuss on Forum
    link: 'https://discourse.gohugo.io'

# Site header

main_menu:
  enable: true
  align: l
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: true

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features

highlight: true
highlight_languages:
  - r
  - python
  - latex
math: false
diagram: false
privacy_pack: false
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false
show_related:
  book: true
  page: false
  post: true
  project: true
  publication: true
  event: true
reading_time: true
section_pager: false
docs_section_pager: true
sharing: true
copyright_license:
  enable: true #false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {creative commons}'
abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: true
comments:
  provider: ''
  commentable:
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: mapnik
  api_key: ''
  zoom: 15
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: master
  local_backend: false
icon:
  pack:
    ai: false
